import { toolbarReducerTypes } from "../../@types/literals"

export const X_REFLECT: toolbarReducerTypes = "X_REFLECT"
export const Y_REFLECT: toolbarReducerTypes = "Y_REFLECT"
export const BRUSH: toolbarReducerTypes = "BRUSH"
export const ERASER: toolbarReducerTypes = "ERASER"
export const FREEHAND: toolbarReducerTypes = "FREEHAND"
export const IDROPPER: toolbarReducerTypes = "IDROPPER"
export const CLEAR: toolbarReducerTypes = "CLEAR"
export const LINE_WIDTH: toolbarReducerTypes = "LINE_WIDTH"
